-- Migration 048 — audit_log_trigger() skip si actor_id null.
--
-- Bug #89 audit Chrome :
-- > 19/500 entrees avec actor_id=null et actor_role="unknown".
-- > Trigger fire dans contexte cron / edge function / service role.
--
-- Fix : si auth.uid() est null, on n'INSERT PAS dans audit_log_entries.
-- Les operations service role sont deja tracees par les Supabase logs natifs
-- (consultables via mcp__supabase__get_logs ou dashboard) — pas de double log.
--
-- Idempotente : CREATE OR REPLACE FUNCTION (combine #91, #90 #92 #105 + #89).

-- (Voir migration appliquee via MCP — corps SQL identique a 046 + check actor_uid is null en debut)
