export const features = {
  dashboard:    true,
  rentabilite:  false,
  statistiques: false,
  livraisons:   true,
  planning:     true,
  calendrier:   false,
  incidents:    false,
  inspections:  false,
  vehicules:    true,
  carburant:    true,
  entretiens:   true,
  clients:      true,
  fournisseurs: true,
  charges:      true,
  encaissement: false,
  tva:          false,
  equipe:       true,
  heures:       false,
  alertes:      false,
  brouillons:   false,
  parametres:   false,
} as const

export type FeatureKey = keyof typeof features
